/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:16f3ffbb-6b76-4b9c-b083-3d5e43404b7e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MSALIO7RV",
    "aws_user_pools_web_client_id": "nsi98llcss8qv6bhks29nu819",
    "API": {
        "endpoints": [
            {
                "name": "private",
                "endpoint": "https://h7hwy6b839.execute-api.us-east-1.amazonaws.com",
                "service": "lambda",
                "region": "us-east-1"
            }
        ]
    }, 
    "oauth": {
        "domain": "facebookeze-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
