/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5bcd5498-0484-45ba-8910-177788fb7cf8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SZ8VNrqWT",
    "aws_user_pools_web_client_id": "4dmb9sspm9k92n4h55kvpmftkt",
    "oauth": {
        "domain": "facebookauth-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://localhost:3000/login/",
        "redirectSignOut": "https://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
